baseURL = "https://www.jakewiesler.com/"
languageCode = "en-us"
title = "Jake Wiesler"
preserveTaxonomyNames = true

[taxonomies]
  tag = "tags"

[params]
  author = "Jake Wiesler"
  description = "Front-end Developer, CSS Tinkerer, and UI Designer."
  twitter = "@jakewies"